version: '3'

services:
  catalog-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${CATALOG_DBNAME}
      - POSTGRES_USER=${CATALOG_DBUSER}
      - POSTGRES_PASSWORD=${CATALOG_DBPASSWORD}
    logging:
      driver: none
    volumes: 
      - catalog-db:/var/lib/postgresql/data
    networks:
      - sb

  catalog:
    build:
      context: ./src/services/catalog
      dockerfile: Dockerfile
    command: python main.py
    working_dir: /usr/bin/catalog
    restart: on-failure
    environment:
      - DBNAME=${CATALOG_DBNAME}
      - DBUSER=${CATALOG_DBUSER}
      - DBPASSWORD=${CATALOG_DBPASSWORD}
      - AMQP_URL=${AMQP_URL}
    networks:
      - sb
    links:
      - rabbitmq
      - catalog-db
    depends_on:
      - rabbitmq
      - catalog-db
    
  orders:
    build:
      context: ./src/services/orders
      dockerfile: Dockerfile
    command: python main.py
    working_dir: /usr/bin/orders
    restart: on-failure
    environment:   
      - SECRET_KEY=${ORDERS_SECRET_KEY}
      - AMQP_URL=${AMQP_URL}
    links:
      - rabbitmq
    networks:
      - sb
    depends_on:
      - rabbitmq

  
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    networks:
      - sb
    ports:
      - 5672:5672
      - 15672:15672


volumes:
  catalog-db:
    driver: local

networks:
    sb:
      driver: bridge